spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    password: s3cr3tz
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  data:
    rest:
      base-path: /api
  jpa:
    hibernate:
      ddl-auto: create
